/*
 * server/serverpb/server.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package apiclient

type ModelNetwork struct {
	Prefix string `json:"prefix,omitempty"`

	Gateways []string `json:"gateways,omitempty"`

	Broadcast string `json:"broadcast,omitempty"`

	Netmask string `json:"netmask,omitempty"`

	Status ModelNetworkStatus `json:"status,omitempty"`

	Tags []ModelTag `json:"tags,omitempty"`
}
