/*
 * server/serverpb/server.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package apiclient

import (
	"time"
)

type ModelIpAddr struct {
	Ip string `json:"ip,omitempty"`

	Status ModelIpAddrStatus `json:"status,omitempty"`

	Tags []ModelTag `json:"tags,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	LastModifiedAt time.Time `json:"last_modified_at,omitempty"`
}
