// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: server/serverpb/server.proto

/*
	Package serverpb is a generated protocol buffer package.

	It is generated from these files:
		server/serverpb/server.proto

	It has these top-level messages:
		DrawIPRequest
		DrawIPResponse
		GetNetworkIncludingIPRequest
		ActivateIPRequest
		ActivateIPResponse
		DeactivateIPRequest
		DeactivateIPResponse
		GetNetworkRequest
		GetNetworkResponse
		CreateNetworkRequest
		CreateNetworkResponse
		CreatePoolRequest
		CreatePoolResponse
*/
package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import model "github.com/taku-k/ipdrawer/pkg/model"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DrawIPRequest struct {
	Ip      string     `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask    int32      `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	PoolTag *model.Tag `protobuf:"bytes,3,opt,name=pool_tag,json=poolTag" json:"pool_tag,omitempty"`
	Name    string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *DrawIPRequest) Reset()                    { *m = DrawIPRequest{} }
func (m *DrawIPRequest) String() string            { return proto.CompactTextString(m) }
func (*DrawIPRequest) ProtoMessage()               {}
func (*DrawIPRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{0} }

func (m *DrawIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DrawIPRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *DrawIPRequest) GetPoolTag() *model.Tag {
	if m != nil {
		return m.PoolTag
	}
	return nil
}

func (m *DrawIPRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DrawIPResponse struct {
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *DrawIPResponse) Reset()                    { *m = DrawIPResponse{} }
func (m *DrawIPResponse) String() string            { return proto.CompactTextString(m) }
func (*DrawIPResponse) ProtoMessage()               {}
func (*DrawIPResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{1} }

func (m *DrawIPResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetNetworkIncludingIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *GetNetworkIncludingIPRequest) Reset()         { *m = GetNetworkIncludingIPRequest{} }
func (m *GetNetworkIncludingIPRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkIncludingIPRequest) ProtoMessage()    {}
func (*GetNetworkIncludingIPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorServer, []int{2}
}

func (m *GetNetworkIncludingIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ActivateIPRequest struct {
	Ip   string       `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Tags []*model.Tag `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
}

func (m *ActivateIPRequest) Reset()                    { *m = ActivateIPRequest{} }
func (m *ActivateIPRequest) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPRequest) ProtoMessage()               {}
func (*ActivateIPRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{3} }

func (m *ActivateIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ActivateIPRequest) GetTags() []*model.Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ActivateIPResponse struct {
}

func (m *ActivateIPResponse) Reset()                    { *m = ActivateIPResponse{} }
func (m *ActivateIPResponse) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPResponse) ProtoMessage()               {}
func (*ActivateIPResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{4} }

type DeactivateIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (m *DeactivateIPRequest) Reset()                    { *m = DeactivateIPRequest{} }
func (m *DeactivateIPRequest) String() string            { return proto.CompactTextString(m) }
func (*DeactivateIPRequest) ProtoMessage()               {}
func (*DeactivateIPRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{5} }

func (m *DeactivateIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type DeactivateIPResponse struct {
}

func (m *DeactivateIPResponse) Reset()                    { *m = DeactivateIPResponse{} }
func (m *DeactivateIPResponse) String() string            { return proto.CompactTextString(m) }
func (*DeactivateIPResponse) ProtoMessage()               {}
func (*DeactivateIPResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{6} }

type GetNetworkRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask int32  `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *GetNetworkRequest) Reset()                    { *m = GetNetworkRequest{} }
func (m *GetNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkRequest) ProtoMessage()               {}
func (*GetNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{7} }

func (m *GetNetworkRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetNetworkRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *GetNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNetworkResponse struct {
	Network         string       `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	DefaultGateways []string     `protobuf:"bytes,2,rep,name=default_gateways,json=defaultGateways" json:"default_gateways,omitempty"`
	Broadcast       string       `protobuf:"bytes,3,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Netmask         string       `protobuf:"bytes,4,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Tags            []*model.Tag `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
}

func (m *GetNetworkResponse) Reset()                    { *m = GetNetworkResponse{} }
func (m *GetNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkResponse) ProtoMessage()               {}
func (*GetNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{8} }

func (m *GetNetworkResponse) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *GetNetworkResponse) GetDefaultGateways() []string {
	if m != nil {
		return m.DefaultGateways
	}
	return nil
}

func (m *GetNetworkResponse) GetBroadcast() string {
	if m != nil {
		return m.Broadcast
	}
	return ""
}

func (m *GetNetworkResponse) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *GetNetworkResponse) GetTags() []*model.Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateNetworkRequest struct {
	Ip              string       `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask            int32        `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	DefaultGateways []string     `protobuf:"bytes,3,rep,name=default_gateways,json=defaultGateways" json:"default_gateways,omitempty"`
	Tags            []*model.Tag `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *CreateNetworkRequest) Reset()                    { *m = CreateNetworkRequest{} }
func (m *CreateNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNetworkRequest) ProtoMessage()               {}
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{9} }

func (m *CreateNetworkRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateNetworkRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *CreateNetworkRequest) GetDefaultGateways() []string {
	if m != nil {
		return m.DefaultGateways
	}
	return nil
}

func (m *CreateNetworkRequest) GetTags() []*model.Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateNetworkResponse struct {
}

func (m *CreateNetworkResponse) Reset()                    { *m = CreateNetworkResponse{} }
func (m *CreateNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNetworkResponse) ProtoMessage()               {}
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{10} }

type CreatePoolRequest struct {
	Ip   string      `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask int32       `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	Pool *model.Pool `protobuf:"bytes,3,opt,name=pool" json:"pool,omitempty"`
}

func (m *CreatePoolRequest) Reset()                    { *m = CreatePoolRequest{} }
func (m *CreatePoolRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePoolRequest) ProtoMessage()               {}
func (*CreatePoolRequest) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{11} }

func (m *CreatePoolRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreatePoolRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *CreatePoolRequest) GetPool() *model.Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type CreatePoolResponse struct {
}

func (m *CreatePoolResponse) Reset()                    { *m = CreatePoolResponse{} }
func (m *CreatePoolResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePoolResponse) ProtoMessage()               {}
func (*CreatePoolResponse) Descriptor() ([]byte, []int) { return fileDescriptorServer, []int{12} }

func init() {
	proto.RegisterType((*DrawIPRequest)(nil), "serverpb.DrawIPRequest")
	proto.RegisterType((*DrawIPResponse)(nil), "serverpb.DrawIPResponse")
	proto.RegisterType((*GetNetworkIncludingIPRequest)(nil), "serverpb.GetNetworkIncludingIPRequest")
	proto.RegisterType((*ActivateIPRequest)(nil), "serverpb.ActivateIPRequest")
	proto.RegisterType((*ActivateIPResponse)(nil), "serverpb.ActivateIPResponse")
	proto.RegisterType((*DeactivateIPRequest)(nil), "serverpb.DeactivateIPRequest")
	proto.RegisterType((*DeactivateIPResponse)(nil), "serverpb.DeactivateIPResponse")
	proto.RegisterType((*GetNetworkRequest)(nil), "serverpb.GetNetworkRequest")
	proto.RegisterType((*GetNetworkResponse)(nil), "serverpb.GetNetworkResponse")
	proto.RegisterType((*CreateNetworkRequest)(nil), "serverpb.CreateNetworkRequest")
	proto.RegisterType((*CreateNetworkResponse)(nil), "serverpb.CreateNetworkResponse")
	proto.RegisterType((*CreatePoolRequest)(nil), "serverpb.CreatePoolRequest")
	proto.RegisterType((*CreatePoolResponse)(nil), "serverpb.CreatePoolResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NetworkServiceV0 service

type NetworkServiceV0Client interface {
	DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error)
}

type networkServiceV0Client struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceV0Client(cc *grpc.ClientConn) NetworkServiceV0Client {
	return &networkServiceV0Client{cc}
}

func (c *networkServiceV0Client) DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error) {
	out := new(DrawIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/DrawIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	out := new(GetNetworkResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/GetNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	out := new(CreateNetworkResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/CreateNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error) {
	out := new(CreatePoolResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/CreatePool", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NetworkServiceV0 service

type NetworkServiceV0Server interface {
	DrawIP(context.Context, *DrawIPRequest) (*DrawIPResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error)
}

func RegisterNetworkServiceV0Server(s *grpc.Server, srv NetworkServiceV0Server) {
	s.RegisterService(&_NetworkServiceV0_serviceDesc, srv)
}

func _NetworkServiceV0_DrawIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).DrawIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/DrawIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).DrawIP(ctx, req.(*DrawIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/GetNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/CreateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/CreatePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkServiceV0_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.NetworkServiceV0",
	HandlerType: (*NetworkServiceV0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DrawIP",
			Handler:    _NetworkServiceV0_DrawIP_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NetworkServiceV0_GetNetwork_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _NetworkServiceV0_CreateNetwork_Handler,
		},
		{
			MethodName: "CreatePool",
			Handler:    _NetworkServiceV0_CreatePool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/serverpb/server.proto",
}

// Client API for IPServiceV0 service

type IPServiceV0Client interface {
	GetNetworkIncludingIP(ctx context.Context, in *GetNetworkIncludingIPRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error)
	DeactivateIP(ctx context.Context, in *DeactivateIPRequest, opts ...grpc.CallOption) (*DeactivateIPResponse, error)
}

type iPServiceV0Client struct {
	cc *grpc.ClientConn
}

func NewIPServiceV0Client(cc *grpc.ClientConn) IPServiceV0Client {
	return &iPServiceV0Client{cc}
}

func (c *iPServiceV0Client) GetNetworkIncludingIP(ctx context.Context, in *GetNetworkIncludingIPRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	out := new(GetNetworkResponse)
	err := grpc.Invoke(ctx, "/serverpb.IPServiceV0/GetNetworkIncludingIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceV0Client) ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error) {
	out := new(ActivateIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.IPServiceV0/ActivateIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceV0Client) DeactivateIP(ctx context.Context, in *DeactivateIPRequest, opts ...grpc.CallOption) (*DeactivateIPResponse, error) {
	out := new(DeactivateIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.IPServiceV0/DeactivateIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IPServiceV0 service

type IPServiceV0Server interface {
	GetNetworkIncludingIP(context.Context, *GetNetworkIncludingIPRequest) (*GetNetworkResponse, error)
	ActivateIP(context.Context, *ActivateIPRequest) (*ActivateIPResponse, error)
	DeactivateIP(context.Context, *DeactivateIPRequest) (*DeactivateIPResponse, error)
}

func RegisterIPServiceV0Server(s *grpc.Server, srv IPServiceV0Server) {
	s.RegisterService(&_IPServiceV0_serviceDesc, srv)
}

func _IPServiceV0_GetNetworkIncludingIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkIncludingIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceV0Server).GetNetworkIncludingIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.IPServiceV0/GetNetworkIncludingIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceV0Server).GetNetworkIncludingIP(ctx, req.(*GetNetworkIncludingIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPServiceV0_ActivateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceV0Server).ActivateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.IPServiceV0/ActivateIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceV0Server).ActivateIP(ctx, req.(*ActivateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPServiceV0_DeactivateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceV0Server).DeactivateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.IPServiceV0/DeactivateIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceV0Server).DeactivateIP(ctx, req.(*DeactivateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IPServiceV0_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.IPServiceV0",
	HandlerType: (*IPServiceV0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkIncludingIP",
			Handler:    _IPServiceV0_GetNetworkIncludingIP_Handler,
		},
		{
			MethodName: "ActivateIP",
			Handler:    _IPServiceV0_ActivateIP_Handler,
		},
		{
			MethodName: "DeactivateIP",
			Handler:    _IPServiceV0_DeactivateIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/serverpb/server.proto",
}

func (m *DrawIPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DrawIPRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Mask != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.Mask))
	}
	if m.PoolTag != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.PoolTag.Size()))
		n1, err := m.PoolTag.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func (m *DrawIPResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DrawIPResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	return i, nil
}

func (m *GetNetworkIncludingIPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNetworkIncludingIPRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	return i, nil
}

func (m *ActivateIPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActivateIPRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			dAtA[i] = 0x12
			i++
			i = encodeVarintServer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ActivateIPResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActivateIPResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *DeactivateIPRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeactivateIPRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	return i, nil
}

func (m *DeactivateIPResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeactivateIPResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *GetNetworkRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNetworkRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Mask != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.Mask))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func (m *GetNetworkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNetworkResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Network) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Network)))
		i += copy(dAtA[i:], m.Network)
	}
	if len(m.DefaultGateways) > 0 {
		for _, s := range m.DefaultGateways {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Broadcast) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Broadcast)))
		i += copy(dAtA[i:], m.Broadcast)
	}
	if len(m.Netmask) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Netmask)))
		i += copy(dAtA[i:], m.Netmask)
	}
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintServer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateNetworkRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateNetworkRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Mask != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.Mask))
	}
	if len(m.DefaultGateways) > 0 {
		for _, s := range m.DefaultGateways {
			dAtA[i] = 0x1a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Tags) > 0 {
		for _, msg := range m.Tags {
			dAtA[i] = 0x22
			i++
			i = encodeVarintServer(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateNetworkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateNetworkResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *CreatePoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePoolRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintServer(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Mask != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.Mask))
	}
	if m.Pool != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintServer(dAtA, i, uint64(m.Pool.Size()))
		n2, err := m.Pool.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *CreatePoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePoolResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64Server(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Server(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintServer(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DrawIPRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if m.Mask != 0 {
		n += 1 + sovServer(uint64(m.Mask))
	}
	if m.PoolTag != nil {
		l = m.PoolTag.Size()
		n += 1 + l + sovServer(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *DrawIPResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *GetNetworkIncludingIPRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *ActivateIPRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovServer(uint64(l))
		}
	}
	return n
}

func (m *ActivateIPResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *DeactivateIPRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *DeactivateIPResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *GetNetworkRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if m.Mask != 0 {
		n += 1 + sovServer(uint64(m.Mask))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *GetNetworkResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if len(m.DefaultGateways) > 0 {
		for _, s := range m.DefaultGateways {
			l = len(s)
			n += 1 + l + sovServer(uint64(l))
		}
	}
	l = len(m.Broadcast)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	l = len(m.Netmask)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovServer(uint64(l))
		}
	}
	return n
}

func (m *CreateNetworkRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if m.Mask != 0 {
		n += 1 + sovServer(uint64(m.Mask))
	}
	if len(m.DefaultGateways) > 0 {
		for _, s := range m.DefaultGateways {
			l = len(s)
			n += 1 + l + sovServer(uint64(l))
		}
	}
	if len(m.Tags) > 0 {
		for _, e := range m.Tags {
			l = e.Size()
			n += 1 + l + sovServer(uint64(l))
		}
	}
	return n
}

func (m *CreateNetworkResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *CreatePoolRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovServer(uint64(l))
	}
	if m.Mask != 0 {
		n += 1 + sovServer(uint64(m.Mask))
	}
	if m.Pool != nil {
		l = m.Pool.Size()
		n += 1 + l + sovServer(uint64(l))
	}
	return n
}

func (m *CreatePoolResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovServer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozServer(x uint64) (n int) {
	return sovServer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DrawIPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DrawIPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DrawIPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mask", wireType)
			}
			m.Mask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mask |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolTag", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PoolTag == nil {
				m.PoolTag = &model.Tag{}
			}
			if err := m.PoolTag.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DrawIPResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DrawIPResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DrawIPResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNetworkIncludingIPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNetworkIncludingIPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNetworkIncludingIPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActivateIPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActivateIPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActivateIPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, &model.Tag{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActivateIPResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActivateIPResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActivateIPResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeactivateIPRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeactivateIPRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeactivateIPRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeactivateIPResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeactivateIPResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeactivateIPResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNetworkRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNetworkRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNetworkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mask", wireType)
			}
			m.Mask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mask |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNetworkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNetworkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNetworkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultGateways", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultGateways = append(m.DefaultGateways, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Broadcast", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Broadcast = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Netmask", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Netmask = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, &model.Tag{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateNetworkRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateNetworkRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateNetworkRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mask", wireType)
			}
			m.Mask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mask |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultGateways", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultGateways = append(m.DefaultGateways, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, &model.Tag{})
			if err := m.Tags[len(m.Tags)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateNetworkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateNetworkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateNetworkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mask", wireType)
			}
			m.Mask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mask |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServer
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pool == nil {
				m.Pool = &model.Pool{}
			}
			if err := m.Pool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipServer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthServer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthServer
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowServer
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipServer(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthServer = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServer   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("server/serverpb/server.proto", fileDescriptorServer) }

var fileDescriptorServer = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x6f, 0xe3, 0x44,
	0x14, 0x67, 0xdc, 0xec, 0x47, 0x5f, 0xe9, 0xd2, 0x0e, 0xdd, 0xad, 0xc9, 0xa6, 0x71, 0x30, 0x2c,
	0x9b, 0x22, 0x1c, 0x67, 0x5d, 0x16, 0x54, 0x24, 0x0e, 0x94, 0x45, 0xab, 0x0a, 0x09, 0x55, 0x61,
	0xc5, 0x61, 0x43, 0x59, 0x4d, 0x92, 0x59, 0x63, 0xe2, 0x78, 0xbc, 0xf6, 0x24, 0x11, 0x4a, 0xcb,
	0x22, 0x0e, 0x2b, 0xf6, 0xc2, 0x05, 0x09, 0x71, 0xe3, 0xc2, 0x85, 0x3b, 0xff, 0x01, 0x17, 0x8e,
	0x20, 0xae, 0x48, 0x45, 0x81, 0x33, 0x27, 0xee, 0x20, 0x8f, 0xc7, 0xb5, 0x1b, 0xbb, 0x05, 0x2e,
	0xfb, 0x91, 0x43, 0x3c, 0xf3, 0xde, 0x1b, 0xbd, 0xdf, 0xfb, 0xcd, 0x7b, 0xf3, 0x1e, 0x54, 0x42,
	0x1a, 0x8c, 0x68, 0x60, 0xc6, 0x1f, 0xbf, 0x23, 0x17, 0x0d, 0x3f, 0x60, 0x9c, 0xe1, 0xb3, 0x89,
	0xb8, 0x5c, 0xb1, 0x19, 0xb3, 0x5d, 0x6a, 0x12, 0xdf, 0x31, 0x89, 0xe7, 0x31, 0x4e, 0xb8, 0xc3,
	0xbc, 0x30, 0xb6, 0x2b, 0xbf, 0x62, 0x3b, 0xfc, 0xc3, 0x61, 0xa7, 0xd1, 0x65, 0x03, 0x73, 0x30,
	0x76, 0x78, 0x9f, 0x8d, 0x4d, 0x9b, 0x19, 0x42, 0x69, 0x8c, 0x88, 0xeb, 0xf4, 0x08, 0x67, 0x41,
	0x68, 0x1e, 0x2e, 0xe5, 0xb9, 0x66, 0xe6, 0x1c, 0x27, 0xfd, 0xa1, 0xd1, 0x37, 0x1d, 0xbf, 0x17,
	0x90, 0x31, 0x0d, 0x4c, 0xbf, 0x6f, 0x9b, 0x03, 0xd6, 0xa3, 0x6e, 0xfc, 0x2f, 0x4f, 0x18, 0x99,
	0x13, 0x36, 0xb3, 0x99, 0x29, 0xc4, 0x9d, 0xe1, 0x6d, 0xb1, 0x13, 0x1b, 0xb1, 0x8a, 0xcd, 0xf5,
	0xbf, 0x10, 0x2c, 0x5e, 0x0b, 0xc8, 0x78, 0x7b, 0xa7, 0x45, 0xef, 0x0c, 0x69, 0xc8, 0xf1, 0xa7,
	0x08, 0x14, 0xc7, 0x57, 0x51, 0x0d, 0xd5, 0xe7, 0xb7, 0xfc, 0xe9, 0x81, 0xe6, 0xc2, 0x47, 0x7b,
	0x1f, 0xd4, 0xeb, 0xed, 0xa6, 0xb1, 0xb9, 0xbb, 0xd7, 0xbe, 0x62, 0x6c, 0xee, 0xc6, 0xcb, 0x2b,
	0xe2, 0x33, 0xb1, 0xf6, 0xf7, 0xac, 0x76, 0xd3, 0x78, 0x59, 0x4a, 0xad, 0xab, 0xed, 0xa6, 0x71,
	0x75, 0x77, 0xfd, 0xfd, 0xc6, 0xfa, 0x64, 0x63, 0xff, 0xff, 0x9e, 0x7a, 0xbe, 0xa5, 0x38, 0x3e,
	0xbe, 0x04, 0xa5, 0x01, 0x09, 0xfb, 0xaa, 0x52, 0x43, 0xf5, 0x53, 0x5b, 0xcb, 0xd3, 0x03, 0x6d,
	0x71, 0xe9, 0xef, 0xe4, 0x87, 0xd4, 0x67, 0x5b, 0x42, 0x8d, 0x2f, 0xc1, 0x59, 0x9f, 0x31, 0xf7,
	0x16, 0x27, 0xb6, 0x3a, 0x57, 0x43, 0xf5, 0x05, 0x0b, 0x1a, 0x31, 0x15, 0x37, 0x88, 0xdd, 0x3a,
	0x13, 0xe9, 0x6e, 0x10, 0x1b, 0x63, 0x28, 0x79, 0x64, 0x40, 0xd5, 0x52, 0x14, 0x51, 0x4b, 0xac,
	0xf5, 0x1a, 0x9c, 0x4b, 0xa2, 0x0e, 0x7d, 0xe6, 0x85, 0x14, 0x9f, 0x4b, 0xa3, 0x8e, 0x30, 0xe8,
	0xdf, 0x20, 0xa8, 0x5c, 0xa7, 0xfc, 0x1d, 0xca, 0xc7, 0x2c, 0xe8, 0x6f, 0x7b, 0x5d, 0x77, 0xd8,
	0x73, 0x3c, 0x3b, 0xe5, 0xe9, 0x6e, 0x86, 0x26, 0x36, 0x3d, 0xd0, 0xfa, 0xe0, 0x3c, 0x50, 0x96,
	0xf4, 0xef, 0x11, 0x2c, 0xbf, 0xd1, 0xe5, 0xce, 0x88, 0x70, 0xfa, 0xe8, 0xc0, 0xc2, 0x55, 0x28,
	0x71, 0x62, 0x87, 0xaa, 0x52, 0x9b, 0x9b, 0xb9, 0x11, 0x21, 0xd7, 0x57, 0x00, 0x67, 0x51, 0xc7,
	0xf4, 0xeb, 0x5f, 0x21, 0x78, 0xfa, 0x1a, 0x25, 0x8f, 0x5c, 0x38, 0xfa, 0x05, 0x58, 0x39, 0x8a,
	0x4b, 0x02, 0xfe, 0x19, 0xc1, 0x72, 0x9a, 0x1f, 0x8f, 0x5f, 0xf1, 0x24, 0x55, 0x31, 0x97, 0xa9,
	0x8a, 0x1f, 0x14, 0xc0, 0xd9, 0x98, 0x64, 0x69, 0x7c, 0x87, 0xe0, 0x8c, 0x17, 0xcb, 0x64, 0x64,
	0x5f, 0xa0, 0xe9, 0x81, 0x76, 0x1f, 0xc1, 0x3d, 0xf4, 0xa0, 0x62, 0x33, 0xeb, 0x59, 0x2b, 0x61,
	0xb2, 0xb9, 0xbb, 0xb7, 0xd1, 0x6e, 0x1a, 0x56, 0x14, 0x78, 0x82, 0x0f, 0xaf, 0xc3, 0x52, 0x8f,
	0xde, 0x26, 0x43, 0x97, 0xdf, 0xb2, 0x09, 0xa7, 0x63, 0xf2, 0x71, 0x9c, 0x89, 0xf3, 0xad, 0xa7,
	0xa4, 0xfc, 0xba, 0x14, 0xe3, 0x0a, 0xcc, 0x77, 0x02, 0x46, 0x7a, 0x5d, 0x12, 0x72, 0x49, 0x43,
	0x2a, 0xc0, 0xaa, 0x88, 0x59, 0x30, 0x19, 0x3f, 0x1c, 0xc9, 0xf6, 0x30, 0xc1, 0x4f, 0x1d, 0x93,
	0xe0, 0xf7, 0x15, 0x58, 0x79, 0x33, 0xa0, 0x84, 0xd3, 0x99, 0xe4, 0x78, 0xe8, 0xa5, 0xf9, 0x1f,
	0x53, 0xa3, 0x88, 0xc3, 0xb9, 0x62, 0x0e, 0x13, 0x2e, 0x4a, 0xc7, 0x70, 0xb1, 0x0a, 0xe7, 0x67,
	0xa8, 0x90, 0xe5, 0xf3, 0x2b, 0x82, 0xe5, 0x58, 0xb3, 0xc3, 0x98, 0xfb, 0xb8, 0x31, 0xa4, 0x41,
	0x29, 0xea, 0x2e, 0xb2, 0xeb, 0x2c, 0xc8, 0xb0, 0x45, 0x24, 0x42, 0x11, 0x3d, 0x72, 0xd9, 0xe8,
	0xe2, 0xa0, 0xad, 0x6f, 0x4b, 0xb0, 0x24, 0x89, 0x78, 0x97, 0x06, 0x23, 0xa7, 0x4b, 0xdf, 0x6b,
	0xe2, 0xcf, 0x11, 0x9c, 0x8e, 0x7b, 0x11, 0x5e, 0x6d, 0x24, 0xe3, 0x44, 0xe3, 0x48, 0x4f, 0x2e,
	0xab, 0x79, 0x85, 0xe4, 0xf1, 0xed, 0xcf, 0x7e, 0xf9, 0xe3, 0x4b, 0xe5, 0x2d, 0xac, 0x8b, 0xc1,
	0x63, 0xd4, 0x34, 0x65, 0x21, 0x98, 0x13, 0xc7, 0xdf, 0x37, 0x27, 0x11, 0xda, 0x7d, 0x33, 0x1a,
	0x18, 0x1c, 0xff, 0xa6, 0x86, 0xd7, 0x72, 0x56, 0x51, 0xdd, 0x27, 0x06, 0xf8, 0x1e, 0x02, 0x48,
	0xeb, 0x1f, 0x5f, 0x4c, 0xbd, 0xe6, 0x5e, 0xba, 0x72, 0xa5, 0x58, 0x29, 0x61, 0xbd, 0x2e, 0x60,
	0xbd, 0x8a, 0x2f, 0x9e, 0x00, 0xeb, 0xa6, 0x8a, 0x2f, 0x14, 0xe3, 0xc1, 0x77, 0x61, 0xf1, 0x48,
	0xda, 0xe0, 0x6a, 0xea, 0xad, 0xa8, 0xb4, 0xca, 0xda, 0xb1, 0x7a, 0x09, 0xc8, 0x10, 0x80, 0x2e,
	0xeb, 0x27, 0xf2, 0xd4, 0x15, 0x47, 0x5f, 0x43, 0x2f, 0xe2, 0x09, 0x40, 0x7a, 0x7f, 0x59, 0x22,
	0x72, 0x39, 0x9b, 0x25, 0x22, 0x7f, 0xe5, 0xba, 0x25, 0xfc, 0xbe, 0xa4, 0x5f, 0x3e, 0xc9, 0x6f,
	0x94, 0x32, 0xa9, 0x73, 0xeb, 0x4f, 0x05, 0x16, 0xb6, 0x77, 0xd2, 0x0c, 0xf9, 0x04, 0xce, 0x17,
	0x4e, 0x22, 0xf8, 0x85, 0xa2, 0x3b, 0xc8, 0x8f, 0x2a, 0xff, 0x72, 0x57, 0x9a, 0x80, 0xf8, 0x0c,
	0x5e, 0x4d, 0x20, 0x3a, 0x7e, 0x8c, 0x2e, 0x79, 0x53, 0x5d, 0x80, 0xb4, 0x63, 0x67, 0xc9, 0xc8,
	0x4d, 0x1f, 0x59, 0x4f, 0x05, 0x4d, 0xfe, 0x39, 0xe1, 0x69, 0x4d, 0x57, 0x67, 0x3d, 0x25, 0xfd,
	0x35, 0xa2, 0xfe, 0x0e, 0x3c, 0x99, 0x6d, 0xb8, 0x78, 0x2d, 0x93, 0xfb, 0xf9, 0x01, 0xa1, 0x5c,
	0x3d, 0x4e, 0x2d, 0x7d, 0xea, 0xc2, 0x67, 0x45, 0x2f, 0xcf, 0xfa, 0xec, 0x1d, 0x5a, 0x6f, 0x2d,
	0xfd, 0x38, 0xad, 0xa2, 0x9f, 0xa6, 0x55, 0xf4, 0xdb, 0xb4, 0x8a, 0xbe, 0xfe, 0xbd, 0xfa, 0x44,
	0xe7, 0xb4, 0x98, 0x8e, 0x37, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x8e, 0x19, 0xb5, 0xfe,
	0x0b, 0x00, 0x00,
}
