// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/serverpb/server.proto

/*
Package serverpb is a generated protocol buffer package.

It is generated from these files:
	server/serverpb/server.proto

It has these top-level messages:
	DrawIPRequest
	DrawIPResponse
	GetPrefixIncludingIPRequest
	GetPrefixIncludingIPResponse
	ActivateIPRequest
	ActivateIPResponse
	Tag
*/
package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DrawIPRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask int32  `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	Tags []*Tag `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *DrawIPRequest) Reset()                    { *m = DrawIPRequest{} }
func (m *DrawIPRequest) String() string            { return proto.CompactTextString(m) }
func (*DrawIPRequest) ProtoMessage()               {}
func (*DrawIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DrawIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DrawIPRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *DrawIPRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type DrawIPResponse struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *DrawIPResponse) Reset()                    { *m = DrawIPResponse{} }
func (m *DrawIPResponse) String() string            { return proto.CompactTextString(m) }
func (*DrawIPResponse) ProtoMessage()               {}
func (*DrawIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DrawIPResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetPrefixIncludingIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *GetPrefixIncludingIPRequest) Reset()                    { *m = GetPrefixIncludingIPRequest{} }
func (m *GetPrefixIncludingIPRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPrefixIncludingIPRequest) ProtoMessage()               {}
func (*GetPrefixIncludingIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPrefixIncludingIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetPrefixIncludingIPResponse struct {
}

func (m *GetPrefixIncludingIPResponse) Reset()                    { *m = GetPrefixIncludingIPResponse{} }
func (m *GetPrefixIncludingIPResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPrefixIncludingIPResponse) ProtoMessage()               {}
func (*GetPrefixIncludingIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ActivateIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *ActivateIPRequest) Reset()                    { *m = ActivateIPRequest{} }
func (m *ActivateIPRequest) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPRequest) ProtoMessage()               {}
func (*ActivateIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ActivateIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ActivateIPResponse struct {
}

func (m *ActivateIPResponse) Reset()                    { *m = ActivateIPResponse{} }
func (m *ActivateIPResponse) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPResponse) ProtoMessage()               {}
func (*ActivateIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Tag struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DrawIPRequest)(nil), "serverpb.DrawIPRequest")
	proto.RegisterType((*DrawIPResponse)(nil), "serverpb.DrawIPResponse")
	proto.RegisterType((*GetPrefixIncludingIPRequest)(nil), "serverpb.GetPrefixIncludingIPRequest")
	proto.RegisterType((*GetPrefixIncludingIPResponse)(nil), "serverpb.GetPrefixIncludingIPResponse")
	proto.RegisterType((*ActivateIPRequest)(nil), "serverpb.ActivateIPRequest")
	proto.RegisterType((*ActivateIPResponse)(nil), "serverpb.ActivateIPResponse")
	proto.RegisterType((*Tag)(nil), "serverpb.Tag")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PrefixService service

type PrefixServiceClient interface {
	DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error)
	GetPrefixIncludingIP(ctx context.Context, in *GetPrefixIncludingIPRequest, opts ...grpc.CallOption) (*GetPrefixIncludingIPResponse, error)
	ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error)
}

type prefixServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrefixServiceClient(cc *grpc.ClientConn) PrefixServiceClient {
	return &prefixServiceClient{cc}
}

func (c *prefixServiceClient) DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error) {
	out := new(DrawIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.PrefixService/DrawIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prefixServiceClient) GetPrefixIncludingIP(ctx context.Context, in *GetPrefixIncludingIPRequest, opts ...grpc.CallOption) (*GetPrefixIncludingIPResponse, error) {
	out := new(GetPrefixIncludingIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.PrefixService/GetPrefixIncludingIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prefixServiceClient) ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error) {
	out := new(ActivateIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.PrefixService/ActivateIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrefixService service

type PrefixServiceServer interface {
	DrawIP(context.Context, *DrawIPRequest) (*DrawIPResponse, error)
	GetPrefixIncludingIP(context.Context, *GetPrefixIncludingIPRequest) (*GetPrefixIncludingIPResponse, error)
	ActivateIP(context.Context, *ActivateIPRequest) (*ActivateIPResponse, error)
}

func RegisterPrefixServiceServer(s *grpc.Server, srv PrefixServiceServer) {
	s.RegisterService(&_PrefixService_serviceDesc, srv)
}

func _PrefixService_DrawIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrefixServiceServer).DrawIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.PrefixService/DrawIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrefixServiceServer).DrawIP(ctx, req.(*DrawIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrefixService_GetPrefixIncludingIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrefixIncludingIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrefixServiceServer).GetPrefixIncludingIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.PrefixService/GetPrefixIncludingIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrefixServiceServer).GetPrefixIncludingIP(ctx, req.(*GetPrefixIncludingIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrefixService_ActivateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrefixServiceServer).ActivateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.PrefixService/ActivateIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrefixServiceServer).ActivateIP(ctx, req.(*ActivateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrefixService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.PrefixService",
	HandlerType: (*PrefixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DrawIP",
			Handler:    _PrefixService_DrawIP_Handler,
		},
		{
			MethodName: "GetPrefixIncludingIP",
			Handler:    _PrefixService_GetPrefixIncludingIP_Handler,
		},
		{
			MethodName: "ActivateIP",
			Handler:    _PrefixService_ActivateIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/serverpb/server.proto",
}

func init() { proto.RegisterFile("server/serverpb/server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x65, 0xa7, 0x8d, 0x60, 0x50, 0x2a, 0xba, 0xb4, 0xaa, 0x95, 0x84, 0xc6, 0xb5, 0x68,
	0xe5, 0x1e, 0x6c, 0xa7, 0x2e, 0x45, 0xea, 0x81, 0x03, 0x15, 0x12, 0xea, 0xad, 0x32, 0x3d, 0x20,
	0x85, 0x20, 0x6d, 0x9c, 0xad, 0x59, 0x25, 0xf1, 0x2e, 0xf6, 0xc6, 0x01, 0xa5, 0x11, 0x52, 0x5f,
	0x01, 0xce, 0xbc, 0x14, 0x37, 0x2e, 0x11, 0x11, 0xef, 0x01, 0xca, 0xae, 0x83, 0xa9, 0x1a, 0x81,
	0xb8, 0x35, 0x97, 0x5d, 0xcd, 0x7f, 0x76, 0xe6, 0x37, 0x1f, 0x31, 0xd4, 0x53, 0x92, 0x64, 0x24,
	0xf1, 0xd4, 0xc1, 0x3b, 0xf9, 0xc5, 0xe5, 0x09, 0x13, 0x0c, 0xdd, 0x59, 0x98, 0xab, 0xf5, 0x88,
	0xb1, 0xa8, 0x4f, 0x3c, 0xcc, 0xa9, 0x87, 0xe3, 0x98, 0x09, 0x2c, 0x28, 0x8b, 0x53, 0xe5, 0x57,
	0x7d, 0x12, 0x51, 0xf1, 0x76, 0xd8, 0x71, 0x43, 0x36, 0xf0, 0x06, 0x23, 0x2a, 0x7a, 0x6c, 0xe4,
	0x45, 0xcc, 0x91, 0xa2, 0x93, 0xe1, 0x3e, 0xed, 0x62, 0xc1, 0x92, 0xd4, 0xfb, 0x7d, 0x55, 0xef,
	0xac, 0x6f, 0x1a, 0x54, 0x9e, 0x27, 0x78, 0x74, 0x7a, 0x16, 0x90, 0x77, 0x43, 0x92, 0x0a, 0xf4,
	0x11, 0x74, 0xca, 0x0d, 0xcd, 0xd4, 0xec, 0xbb, 0x27, 0x6c, 0x36, 0x6d, 0xf4, 0x80, 0xbe, 0xb1,
	0xed, 0x56, 0xd3, 0x39, 0x6e, 0x5f, 0xb6, 0x0e, 0x9c, 0xe3, 0xb6, 0xba, 0x1e, 0xc8, 0x63, 0xec,
	0x4f, 0x2e, 0xfd, 0x56, 0xd3, 0x79, 0x9c, 0x5b, 0xfd, 0xa3, 0x56, 0xd3, 0x39, 0x6a, 0xef, 0xbf,
	0x76, 0xf7, 0xc7, 0x87, 0x93, 0xff, 0x7d, 0xf5, 0x28, 0xd0, 0x29, 0x47, 0xbb, 0xb0, 0x32, 0xc0,
	0x69, 0xcf, 0xd0, 0x4d, 0xcd, 0x5e, 0x3d, 0x59, 0x9f, 0x4d, 0x1b, 0x95, 0xfb, 0x3f, 0x17, 0x3f,
	0xcd, 0xd8, 0x09, 0xa4, 0x8c, 0x76, 0x60, 0x45, 0xe0, 0x28, 0x35, 0x4a, 0x66, 0xc9, 0xbe, 0xe7,
	0x57, 0xdc, 0x45, 0xa3, 0xdc, 0x73, 0x1c, 0x05, 0x52, 0xb2, 0x4c, 0x58, 0x5b, 0xd4, 0x96, 0x72,
	0x16, 0xa7, 0x04, 0xad, 0x15, 0xc5, 0xcd, 0x73, 0x59, 0x5f, 0x34, 0xa8, 0xbd, 0x20, 0xe2, 0x2c,
	0x21, 0x17, 0xf4, 0xfd, 0x69, 0x1c, 0xf6, 0x87, 0x5d, 0x1a, 0x47, 0xb7, 0xa7, 0x19, 0xd6, 0x36,
	0xd4, 0x97, 0xf3, 0xa9, 0x82, 0xac, 0xcf, 0x1a, 0xac, 0x3f, 0x0b, 0x05, 0xcd, 0xb0, 0x20, 0xb7,
	0x08, 0x7b, 0x03, 0xd0, 0x9f, 0x54, 0x39, 0xec, 0x53, 0x28, 0x9d, 0xe3, 0x08, 0x19, 0x50, 0xea,
	0x91, 0x0f, 0x39, 0x5e, 0x79, 0x36, 0x6d, 0xe8, 0xaf, 0xb4, 0x60, 0x6e, 0x42, 0x75, 0x58, 0xcd,
	0x70, 0x7f, 0x48, 0xe4, 0xec, 0x0b, 0x4d, 0x19, 0xfd, 0xef, 0x3a, 0x54, 0x54, 0x27, 0x5e, 0x92,
	0x24, 0xa3, 0x21, 0x41, 0x21, 0x94, 0xd5, 0x80, 0xd1, 0x56, 0x31, 0xff, 0x6b, 0xeb, 0x5c, 0x35,
	0x6e, 0x0a, 0x39, 0xcd, 0xde, 0xd5, 0xd7, 0x1f, 0x9f, 0x74, 0x13, 0x6d, 0xcb, 0xbf, 0x14, 0x97,
	0x81, 0xbd, 0x31, 0xe5, 0x13, 0x6f, 0x3c, 0x5f, 0xb0, 0x89, 0xd7, 0x4d, 0xf0, 0x88, 0x72, 0x74,
	0xa5, 0xc1, 0xc6, 0xb2, 0x19, 0xa0, 0xdd, 0x22, 0xf4, 0x5f, 0x76, 0xa8, 0xba, 0xf7, 0x2f, 0xb7,
	0x9c, 0xa7, 0x26, 0x79, 0x36, 0xd1, 0x03, 0xc9, 0x43, 0xb9, 0x62, 0x51, 0x5c, 0xe8, 0x02, 0xa0,
	0x68, 0x28, 0xaa, 0x15, 0x21, 0x6f, 0x0c, 0xbf, 0x5a, 0x5f, 0x2e, 0xe6, 0x59, 0x1e, 0xca, 0x2c,
	0x5b, 0xd6, 0xe6, 0xb5, 0x2c, 0x38, 0x77, 0xec, 0x94, 0xe5, 0x67, 0xe1, 0xf0, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0xbe, 0xd0, 0x51, 0x96, 0x04, 0x00, 0x00,
}
