// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/serverpb/server.proto

/*
Package serverpb is a generated protocol buffer package.

It is generated from these files:
	server/serverpb/server.proto

It has these top-level messages:
	DrawIPRequest
	DrawIPResponse
	GetNetworkIncludingIPRequest
	GetNetworkIncludingIPResponse
	ActivateIPRequest
	ActivateIPResponse
	GetNetworkRequest
	GetNetworkResponse
	CreateNetworkRequest
	CreateNetworkResponse
	CreatePoolRequest
	CreatePoolResponse
	Tag
	Pool
*/
package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DrawIPRequest struct {
	Ip      string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask    int32  `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	PoolTag *Tag   `protobuf:"bytes,3,opt,name=pool_tag,json=poolTag" json:"pool_tag,omitempty"`
	Name    string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *DrawIPRequest) Reset()                    { *m = DrawIPRequest{} }
func (m *DrawIPRequest) String() string            { return proto.CompactTextString(m) }
func (*DrawIPRequest) ProtoMessage()               {}
func (*DrawIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DrawIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DrawIPRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *DrawIPRequest) GetPoolTag() *Tag {
	if m != nil {
		return m.PoolTag
	}
	return nil
}

func (m *DrawIPRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DrawIPResponse struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *DrawIPResponse) Reset()                    { *m = DrawIPResponse{} }
func (m *DrawIPResponse) String() string            { return proto.CompactTextString(m) }
func (*DrawIPResponse) ProtoMessage()               {}
func (*DrawIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DrawIPResponse) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetNetworkIncludingIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *GetNetworkIncludingIPRequest) Reset()                    { *m = GetNetworkIncludingIPRequest{} }
func (m *GetNetworkIncludingIPRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkIncludingIPRequest) ProtoMessage()               {}
func (*GetNetworkIncludingIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetNetworkIncludingIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetNetworkIncludingIPResponse struct {
}

func (m *GetNetworkIncludingIPResponse) Reset()                    { *m = GetNetworkIncludingIPResponse{} }
func (m *GetNetworkIncludingIPResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkIncludingIPResponse) ProtoMessage()               {}
func (*GetNetworkIncludingIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ActivateIPRequest struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *ActivateIPRequest) Reset()                    { *m = ActivateIPRequest{} }
func (m *ActivateIPRequest) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPRequest) ProtoMessage()               {}
func (*ActivateIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ActivateIPRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ActivateIPResponse struct {
}

func (m *ActivateIPResponse) Reset()                    { *m = ActivateIPResponse{} }
func (m *ActivateIPResponse) String() string            { return proto.CompactTextString(m) }
func (*ActivateIPResponse) ProtoMessage()               {}
func (*ActivateIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetNetworkRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask int32  `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *GetNetworkRequest) Reset()                    { *m = GetNetworkRequest{} }
func (m *GetNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkRequest) ProtoMessage()               {}
func (*GetNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetNetworkRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetNetworkRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *GetNetworkRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNetworkResponse struct {
	Network         string   `protobuf:"bytes,1,opt,name=network" json:"network,omitempty"`
	DefaultGateways []string `protobuf:"bytes,2,rep,name=default_gateways,json=defaultGateways" json:"default_gateways,omitempty"`
	Broadcast       string   `protobuf:"bytes,3,opt,name=broadcast" json:"broadcast,omitempty"`
	Netmask         string   `protobuf:"bytes,4,opt,name=netmask" json:"netmask,omitempty"`
	Tags            []*Tag   `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
}

func (m *GetNetworkResponse) Reset()                    { *m = GetNetworkResponse{} }
func (m *GetNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNetworkResponse) ProtoMessage()               {}
func (*GetNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetNetworkResponse) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *GetNetworkResponse) GetDefaultGateways() []string {
	if m != nil {
		return m.DefaultGateways
	}
	return nil
}

func (m *GetNetworkResponse) GetBroadcast() string {
	if m != nil {
		return m.Broadcast
	}
	return ""
}

func (m *GetNetworkResponse) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *GetNetworkResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateNetworkRequest struct {
	Ip              string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask            int32    `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	DefaultGateways []string `protobuf:"bytes,3,rep,name=default_gateways,json=defaultGateways" json:"default_gateways,omitempty"`
	Tags            []*Tag   `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *CreateNetworkRequest) Reset()                    { *m = CreateNetworkRequest{} }
func (m *CreateNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNetworkRequest) ProtoMessage()               {}
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateNetworkRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreateNetworkRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *CreateNetworkRequest) GetDefaultGateways() []string {
	if m != nil {
		return m.DefaultGateways
	}
	return nil
}

func (m *CreateNetworkRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateNetworkResponse struct {
}

func (m *CreateNetworkResponse) Reset()                    { *m = CreateNetworkResponse{} }
func (m *CreateNetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNetworkResponse) ProtoMessage()               {}
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type CreatePoolRequest struct {
	Ip   string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Mask int32  `protobuf:"varint,2,opt,name=mask" json:"mask,omitempty"`
	Pool *Pool  `protobuf:"bytes,3,opt,name=pool" json:"pool,omitempty"`
}

func (m *CreatePoolRequest) Reset()                    { *m = CreatePoolRequest{} }
func (m *CreatePoolRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePoolRequest) ProtoMessage()               {}
func (*CreatePoolRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreatePoolRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CreatePoolRequest) GetMask() int32 {
	if m != nil {
		return m.Mask
	}
	return 0
}

func (m *CreatePoolRequest) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type CreatePoolResponse struct {
}

func (m *CreatePoolResponse) Reset()                    { *m = CreatePoolResponse{} }
func (m *CreatePoolResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePoolResponse) ProtoMessage()               {}
func (*CreatePoolResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Tag struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Pool struct {
	Start  string `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End    string `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	Status int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Tags   []*Tag `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *Pool) Reset()                    { *m = Pool{} }
func (m *Pool) String() string            { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()               {}
func (*Pool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Pool) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *Pool) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *Pool) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Pool) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*DrawIPRequest)(nil), "serverpb.DrawIPRequest")
	proto.RegisterType((*DrawIPResponse)(nil), "serverpb.DrawIPResponse")
	proto.RegisterType((*GetNetworkIncludingIPRequest)(nil), "serverpb.GetNetworkIncludingIPRequest")
	proto.RegisterType((*GetNetworkIncludingIPResponse)(nil), "serverpb.GetNetworkIncludingIPResponse")
	proto.RegisterType((*ActivateIPRequest)(nil), "serverpb.ActivateIPRequest")
	proto.RegisterType((*ActivateIPResponse)(nil), "serverpb.ActivateIPResponse")
	proto.RegisterType((*GetNetworkRequest)(nil), "serverpb.GetNetworkRequest")
	proto.RegisterType((*GetNetworkResponse)(nil), "serverpb.GetNetworkResponse")
	proto.RegisterType((*CreateNetworkRequest)(nil), "serverpb.CreateNetworkRequest")
	proto.RegisterType((*CreateNetworkResponse)(nil), "serverpb.CreateNetworkResponse")
	proto.RegisterType((*CreatePoolRequest)(nil), "serverpb.CreatePoolRequest")
	proto.RegisterType((*CreatePoolResponse)(nil), "serverpb.CreatePoolResponse")
	proto.RegisterType((*Tag)(nil), "serverpb.Tag")
	proto.RegisterType((*Pool)(nil), "serverpb.Pool")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NetworkServiceV0 service

type NetworkServiceV0Client interface {
	DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error)
}

type networkServiceV0Client struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceV0Client(cc *grpc.ClientConn) NetworkServiceV0Client {
	return &networkServiceV0Client{cc}
}

func (c *networkServiceV0Client) DrawIP(ctx context.Context, in *DrawIPRequest, opts ...grpc.CallOption) (*DrawIPResponse, error) {
	out := new(DrawIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/DrawIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	out := new(GetNetworkResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/GetNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	out := new(CreateNetworkResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/CreateNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceV0Client) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error) {
	out := new(CreatePoolResponse)
	err := grpc.Invoke(ctx, "/serverpb.NetworkServiceV0/CreatePool", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NetworkServiceV0 service

type NetworkServiceV0Server interface {
	DrawIP(context.Context, *DrawIPRequest) (*DrawIPResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error)
}

func RegisterNetworkServiceV0Server(s *grpc.Server, srv NetworkServiceV0Server) {
	s.RegisterService(&_NetworkServiceV0_serviceDesc, srv)
}

func _NetworkServiceV0_DrawIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).DrawIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/DrawIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).DrawIP(ctx, req.(*DrawIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/GetNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/CreateNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkServiceV0_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceV0Server).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.NetworkServiceV0/CreatePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceV0Server).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkServiceV0_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.NetworkServiceV0",
	HandlerType: (*NetworkServiceV0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DrawIP",
			Handler:    _NetworkServiceV0_DrawIP_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NetworkServiceV0_GetNetwork_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _NetworkServiceV0_CreateNetwork_Handler,
		},
		{
			MethodName: "CreatePool",
			Handler:    _NetworkServiceV0_CreatePool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/serverpb/server.proto",
}

// Client API for IPServiceV0 service

type IPServiceV0Client interface {
	GetNetworkIncludingIP(ctx context.Context, in *GetNetworkIncludingIPRequest, opts ...grpc.CallOption) (*GetNetworkIncludingIPResponse, error)
	ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error)
}

type iPServiceV0Client struct {
	cc *grpc.ClientConn
}

func NewIPServiceV0Client(cc *grpc.ClientConn) IPServiceV0Client {
	return &iPServiceV0Client{cc}
}

func (c *iPServiceV0Client) GetNetworkIncludingIP(ctx context.Context, in *GetNetworkIncludingIPRequest, opts ...grpc.CallOption) (*GetNetworkIncludingIPResponse, error) {
	out := new(GetNetworkIncludingIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.IPServiceV0/GetNetworkIncludingIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceV0Client) ActivateIP(ctx context.Context, in *ActivateIPRequest, opts ...grpc.CallOption) (*ActivateIPResponse, error) {
	out := new(ActivateIPResponse)
	err := grpc.Invoke(ctx, "/serverpb.IPServiceV0/ActivateIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IPServiceV0 service

type IPServiceV0Server interface {
	GetNetworkIncludingIP(context.Context, *GetNetworkIncludingIPRequest) (*GetNetworkIncludingIPResponse, error)
	ActivateIP(context.Context, *ActivateIPRequest) (*ActivateIPResponse, error)
}

func RegisterIPServiceV0Server(s *grpc.Server, srv IPServiceV0Server) {
	s.RegisterService(&_IPServiceV0_serviceDesc, srv)
}

func _IPServiceV0_GetNetworkIncludingIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkIncludingIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceV0Server).GetNetworkIncludingIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.IPServiceV0/GetNetworkIncludingIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceV0Server).GetNetworkIncludingIP(ctx, req.(*GetNetworkIncludingIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPServiceV0_ActivateIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceV0Server).ActivateIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.IPServiceV0/ActivateIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceV0Server).ActivateIP(ctx, req.(*ActivateIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IPServiceV0_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.IPServiceV0",
	HandlerType: (*IPServiceV0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetworkIncludingIP",
			Handler:    _IPServiceV0_GetNetworkIncludingIP_Handler,
		},
		{
			MethodName: "ActivateIP",
			Handler:    _IPServiceV0_ActivateIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/serverpb/server.proto",
}

func init() { proto.RegisterFile("server/serverpb/server.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 904 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xd6, 0x78, 0xbd, 0x69, 0xf3, 0xaa, 0x84, 0x64, 0xd4, 0x36, 0x66, 0xbb, 0xc5, 0x5b, 0x0b,
	0x88, 0x83, 0xf0, 0x7a, 0xeb, 0x50, 0x50, 0x90, 0x38, 0x50, 0x40, 0x55, 0x84, 0x84, 0x22, 0x53,
	0x21, 0xd4, 0x25, 0x54, 0x93, 0xdd, 0xc1, 0x98, 0x75, 0x3c, 0xc6, 0x9e, 0xdd, 0x55, 0xb5, 0x89,
	0x0a, 0x08, 0x2a, 0x2a, 0x21, 0x2e, 0x70, 0xe7, 0xc2, 0x85, 0x3f, 0xc2, 0x8d, 0x03, 0xe2, 0x07,
	0xac, 0xb4, 0xe2, 0x3f, 0x70, 0x04, 0x79, 0x3c, 0xc6, 0x6e, 0xd6, 0x09, 0xe5, 0x92, 0x36, 0xb9,
	0xec, 0xf8, 0xbd, 0x37, 0x79, 0xdf, 0xf7, 0xf9, 0xbd, 0xe7, 0x07, 0xcd, 0x84, 0xc6, 0x23, 0x1a,
	0xdb, 0xd9, 0x4f, 0xb4, 0x27, 0x0f, 0xed, 0x28, 0x66, 0x9c, 0xe1, 0xf3, 0xb9, 0xb9, 0xd1, 0xf4,
	0x18, 0xf3, 0x02, 0x6a, 0x93, 0xc8, 0xb7, 0x49, 0x18, 0x32, 0x4e, 0xb8, 0xcf, 0xc2, 0x24, 0x8b,
	0x6b, 0xbc, 0xea, 0xf9, 0xfc, 0xd3, 0xe1, 0x5e, 0xbb, 0xc7, 0xf6, 0xed, 0xfd, 0xb1, 0xcf, 0x07,
	0x6c, 0x6c, 0x7b, 0xcc, 0x12, 0x4e, 0x6b, 0x44, 0x02, 0xbf, 0x4f, 0x38, 0x8b, 0x13, 0xfb, 0xdf,
	0x63, 0x76, 0xcf, 0xf8, 0x0b, 0xc1, 0xd2, 0xdb, 0x31, 0x19, 0x6f, 0xef, 0xb8, 0xf4, 0xf3, 0x21,
	0x4d, 0x38, 0xfe, 0x02, 0x81, 0xe2, 0x47, 0x1a, 0x6a, 0x21, 0x73, 0xf1, 0x66, 0x34, 0x9b, 0xea,
	0x01, 0x7c, 0x76, 0xf0, 0xb1, 0x69, 0x76, 0x3b, 0xd6, 0xd6, 0xee, 0x41, 0xf7, 0xba, 0xb5, 0xb5,
	0x9b, 0x1d, 0xaf, 0x8b, 0x9f, 0x89, 0x73, 0x78, 0xe0, 0x74, 0x3b, 0xd6, 0x2b, 0xd2, 0xea, 0xdc,
	0xe8, 0x76, 0xac, 0x1b, 0xbb, 0x1b, 0x1f, 0xb5, 0x37, 0x26, 0x9b, 0x87, 0xff, 0xf7, 0xd6, 0xf3,
	0xae, 0xe2, 0x47, 0xf8, 0x05, 0x50, 0xf7, 0x49, 0x32, 0xd0, 0x94, 0x16, 0x32, 0xeb, 0x37, 0x57,
	0x67, 0x53, 0x7d, 0x69, 0xe5, 0xef, 0xfc, 0x0f, 0x69, 0xd7, 0x5c, 0xe1, 0xc6, 0x26, 0x9c, 0x8f,
	0x18, 0x0b, 0xee, 0x72, 0xe2, 0x69, 0xb5, 0x16, 0x32, 0x2f, 0x38, 0x4b, 0xed, 0x5c, 0xae, 0xf6,
	0x6d, 0xe2, 0xb9, 0xe7, 0x52, 0xf7, 0x6d, 0xe2, 0x61, 0x0c, 0x6a, 0x48, 0xf6, 0xa9, 0xa6, 0xa6,
	0xa4, 0x5c, 0x71, 0x36, 0x5a, 0xb0, 0x9c, 0x13, 0x4f, 0x22, 0x16, 0x26, 0x14, 0x2f, 0x17, 0xc4,
	0x53, 0x18, 0xc6, 0x4f, 0x08, 0x9a, 0xb7, 0x28, 0x7f, 0x8f, 0xf2, 0x31, 0x8b, 0x07, 0xdb, 0x61,
	0x2f, 0x18, 0xf6, 0xfd, 0xd0, 0x2b, 0xa4, 0xba, 0x5f, 0x52, 0x8a, 0xcd, 0xa6, 0xfa, 0x00, 0xfc,
	0x53, 0x15, 0xca, 0xd0, 0xe1, 0xea, 0x31, 0x00, 0x33, 0x4a, 0xc6, 0x8f, 0x08, 0x56, 0xdf, 0xec,
	0x71, 0x7f, 0x44, 0x38, 0x7d, 0x8a, 0x70, 0x5f, 0x04, 0x5c, 0x46, 0x25, 0xc1, 0xfe, 0x8e, 0x60,
	0xb5, 0xa0, 0x73, 0xf6, 0xea, 0x31, 0xaf, 0xb2, 0x5a, 0xa9, 0xca, 0x7e, 0x55, 0x00, 0x97, 0x39,
	0xc9, 0x52, 0xfb, 0x05, 0xc1, 0xb9, 0x30, 0xb3, 0x49, 0x66, 0xdf, 0xa3, 0xd9, 0x54, 0x7f, 0x88,
	0xe0, 0x01, 0x3a, 0x2d, 0x6e, 0xb6, 0x59, 0x8e, 0x12, 0x21, 0x5b, 0xbb, 0x07, 0x9b, 0xdd, 0x8e,
	0xe5, 0xa4, 0xc4, 0x73, 0x7c, 0x78, 0x03, 0x56, 0xfa, 0xf4, 0x13, 0x32, 0x0c, 0xf8, 0x5d, 0x8f,
	0x70, 0x3a, 0x26, 0xf7, 0x12, 0x4d, 0x69, 0xd5, 0xcc, 0x45, 0xf7, 0x19, 0x69, 0xbf, 0x25, 0xcd,
	0xb8, 0x09, 0x8b, 0x7b, 0x31, 0x23, 0xfd, 0x1e, 0x49, 0xb8, 0x94, 0xa1, 0x30, 0x60, 0x4d, 0x70,
	0x16, 0x4a, 0x66, 0x8d, 0x98, 0x3f, 0xe2, 0x6b, 0xa0, 0x72, 0xe2, 0x25, 0x5a, 0xbd, 0x55, 0x9b,
	0xef, 0x62, 0xe1, 0x32, 0xbe, 0x53, 0xe0, 0xe2, 0x5b, 0x31, 0x25, 0x9c, 0x1e, 0xa9, 0x8f, 0x27,
	0x5d, 0xcc, 0x8f, 0x5b, 0x1d, 0x55, 0x32, 0xd6, 0xaa, 0x65, 0xcc, 0xe5, 0x50, 0x8f, 0x97, 0x63,
	0x0d, 0x2e, 0x1d, 0x51, 0x43, 0x36, 0xd1, 0x14, 0xc1, 0x6a, 0xe6, 0xd9, 0x61, 0x2c, 0x38, 0x6b,
	0x22, 0x19, 0xa0, 0xa6, 0x33, 0x5b, 0x8e, 0xf3, 0xe5, 0x82, 0xb9, 0x20, 0x23, 0x7c, 0xe9, 0xf0,
	0x28, 0x13, 0x94, 0xbc, 0xdf, 0x80, 0x5a, 0x3a, 0xe9, 0x35, 0xa8, 0x0d, 0xe8, 0x3d, 0xc9, 0x74,
	0x61, 0x36, 0xd5, 0x95, 0x0f, 0x91, 0x9b, 0x9a, 0x70, 0x13, 0xea, 0x23, 0x12, 0x0c, 0xa9, 0x80,
	0x50, 0xf8, 0x32, 0xa3, 0xf1, 0x9b, 0x02, 0x6a, 0xfa, 0xff, 0xf0, 0x37, 0x08, 0xea, 0x09, 0x27,
	0x31, 0x7f, 0x52, 0x6a, 0x65, 0xd9, 0xf1, 0x97, 0x08, 0x6a, 0x34, 0xec, 0x4b, 0xb4, 0xa7, 0x8e,
	0x22, 0xcd, 0x8d, 0x2f, 0xc3, 0x42, 0xc2, 0x09, 0x1f, 0x26, 0xe2, 0x7d, 0xd4, 0x5d, 0xf9, 0xf4,
	0x18, 0xf5, 0xe9, 0xfc, 0xac, 0xc2, 0x8a, 0x2c, 0xcd, 0xf7, 0x69, 0x3c, 0xf2, 0x7b, 0xf4, 0x83,
	0x0e, 0xfe, 0x16, 0xc1, 0x42, 0xf6, 0xcd, 0xc5, 0x6b, 0xc5, 0xa5, 0x47, 0xd6, 0x8f, 0x86, 0x36,
	0xef, 0x90, 0x6f, 0xf8, 0xdd, 0xaf, 0xfe, 0xf8, 0xf3, 0x07, 0xe5, 0x1d, 0x6c, 0x88, 0x15, 0x68,
	0xd4, 0xb1, 0xe5, 0x80, 0xb2, 0x27, 0x7e, 0x74, 0x68, 0x4f, 0xd2, 0xfa, 0x39, 0xb4, 0xfb, 0x31,
	0x19, 0xfb, 0xd1, 0x1d, 0x1d, 0x5f, 0x9d, 0x8b, 0x4a, 0xe7, 0x71, 0x1e, 0x80, 0x1f, 0x20, 0x80,
	0x62, 0x2e, 0xe3, 0x2b, 0x45, 0xd6, 0xb9, 0x2f, 0x50, 0xa3, 0x59, 0xed, 0xcc, 0x0b, 0x4f, 0xc0,
	0x7a, 0x0d, 0x5f, 0x39, 0x01, 0xd6, 0x1d, 0x0d, 0x5f, 0xae, 0xc6, 0x83, 0xef, 0xc3, 0xd2, 0x23,
	0x8d, 0x8c, 0x9f, 0x2b, 0xb2, 0x55, 0xcd, 0xbb, 0x86, 0x7e, 0xac, 0x5f, 0x02, 0xb2, 0x04, 0xa0,
	0x75, 0xe3, 0x44, 0x9d, 0x7a, 0xe2, 0xea, 0xeb, 0xe8, 0x25, 0x3c, 0x01, 0x28, 0xda, 0xa9, 0x2c,
	0xc4, 0xdc, 0x14, 0x29, 0x0b, 0x51, 0xd1, 0x81, 0x8e, 0xc8, 0xfb, 0xb2, 0xb1, 0x7e, 0x52, 0xde,
	0xb4, 0x83, 0x8b, 0xe4, 0xce, 0xd7, 0x0a, 0x5c, 0xd8, 0xde, 0x29, 0x2a, 0xe4, 0x21, 0x82, 0x4b,
	0x95, 0x1b, 0x0d, 0x7e, 0xb1, 0xea, 0x25, 0xcc, 0xef, 0x64, 0x8d, 0xf5, 0xff, 0x8c, 0x93, 0x70,
	0x75, 0x01, 0xf7, 0x59, 0xbc, 0x96, 0xc3, 0xf5, 0xa3, 0x0c, 0x69, 0xfe, 0xdd, 0xf3, 0x01, 0x8a,
	0x25, 0xa5, 0x2c, 0xcc, 0xdc, 0x42, 0x55, 0x16, 0xa6, 0x62, 0xaf, 0x69, 0x89, 0x4c, 0x0d, 0x43,
	0x3b, 0x9a, 0x89, 0xc8, 0xd8, 0xbd, 0x05, 0xb1, 0x8c, 0x6f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x98, 0x65, 0xdc, 0x0c, 0x0c, 0x00, 0x00,
}
