export const REQUEST_IPADDRS = 'REQUEST_IPADDRS';
export const RECEIVE_IPADDRS = 'RECEIVE_IPADDRS';

export const REQUEST_LIST_NETWORK = 'REQUEST_LIST_NETWORK';
export const RECEIVE_LIST_NETWORK = 'RECEIVE_LIST_NETWORK';
