export const REQUEST_IPADDRS = 'REQUEST_IPADDRS';
export const RECEIVE_IPADDRS = 'RECEIVE_IPADDRS';

export const REQUEST_LIST_TEMP_RESERVED_IPS = 'REQUEST_LIST_TEMP_RESERVED_IPS';
export const RECEIVE_LIST_TEMP_RESERVED_IPS = 'RECEIVE_LIST_TEMP_RESERVED_IPS';

export const REQUEST_LIST_NETWORK = 'REQUEST_LIST_NETWORK';
export const RECEIVE_LIST_NETWORK = 'RECEIVE_LIST_NETWORK';

export const REQUEST_LIST_POOL = 'REQUEST_LIST_POOL';
export const RECEIVE_LIST_POOL = 'RECEIVE_LIST_POOL';
